/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicioMeritoSwing;

import exercicioMeritoBeans.PessoaBean;
import exercicioMeritoConnections.Conexao;
import exercicioMeritoControls.PessoaControl;
import exercicioMeritoTools.Tools;
import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Victória
 */
public class CadPessoas extends javax.swing.JFrame {
    
    private final PessoaControl pessoaControl = new PessoaControl();
    private DefaultTableModel tmConsulta = new DefaultTableModel(null, new String[]{"Nome", "Idade", "Documento", "Celular"});
    private ListSelectionModel lsmCobnsulta;
    private List<PessoaBean>pessoas;
    private Boolean inicializando = true;
    /**
     * Creates new form CadPessoas
     */
    public CadPessoas() {
        initComponents();        
        Toolkit kit  = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("user.png");
        this.setIconImage(img);
        desabilitarCanmpos();
        
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centro.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        tbConsultas.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbConsultas.getColumnModel().getColumn(1).setPreferredWidth(10);
        tbConsultas.getColumnModel().getColumn(2).setPreferredWidth(100);
        tbConsultas.getColumnModel().getColumn(3).setPreferredWidth(20);
        
        tbConsultas.getColumnModel().getColumn(0).setCellRenderer(direita);
        tbConsultas.setAutoCreateRowSorter(true);
        tbConsultas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                tbConsultaLinhaSelecionada(tbConsultas);
            }
        });
        listar();
        
    }
    
    private void habilitarCampos(){
        tfNome.setEditable(true);
        tfIdade.setEditable(true);
        tfDocumento.setEditable(true);
        tfTelefone.setEditable(true);
        tfEmail.setEditable(true);
        btExcluir.setEnabled(true);
        btSalvar.setEnabled(true);
    }
    
    private void desabilitarCanmpos(){
        tfNome.setEditable(false);
        tfIdade.setEditable(false);
        tfDocumento.setEditable(false);
        tfTelefone.setEditable(false);
        tfEmail.setEditable(false);
        btExcluir.setEnabled(false);
        btSalvar.setEnabled(false);
    }
    
    private boolean verificaCampos(){
        if(tfNome.getText().trim().isEmpty() || tfIdade.getText().trim().isEmpty()
                || tfDocumento.getText().trim().isEmpty() || tfTelefone.getText().trim().isEmpty()
                || tfEmail.getText().trim().isEmpty()){
            return false;            
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfIdade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btAdc = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        tbConsultas.setModel(tmConsulta);
        jScrollPane1.setViewportView(tbConsultas);

        jLabel1.setText("Nome:");

        jLabel2.setText("Idade:");

        jLabel3.setText("CPF/CNPJ");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("sem caracteres especiais");

        tfTipo.setEditable(false);

        jLabel5.setText("Tipo Pessoa:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("Email:");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btAdc.setText("+");
        btAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdcActionPerformed(evt);
            }
        });

        btExcluir.setText("-");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tfId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(13, 13, 13))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btSalvar)))
                        .addGap(0, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdc)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdcActionPerformed
       habilitarCampos();
    }//GEN-LAST:event_btAdcActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       salvar();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void salvar(){
        if(verificaCampos()){
            try{
                PessoaBean pessoaBean = new PessoaBean();
                int tipo;
                pessoaBean.setNome(tfNome.getText());
                pessoaBean.setIdade(Integer.parseInt(tfIdade.getText()));
                pessoaBean.setDoc(Long.parseLong(tfDocumento.getText()));
                pessoaBean.setEmail(tfEmail.getText());
                pessoaBean.setTelefone(Long.parseLong(tfTelefone.getText()));
                if(tipoDocumento()){
                    if(tfId.getText().trim().isEmpty()){
                        pessoaBean.setId(Tools.gerarId("tb_pessoa_id","tb_pessoas"));
                        pessoaControl.cadastrar(pessoaBean);
                        limparCampos();
                    } else {
                        pessoaBean.setId(Long.parseLong(tfId.getText()));
                        pessoaControl.alterar(pessoaBean);
                        limparCampos();
                    }
                } else {
                   JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar este usuário");
                } 
                listar();
            } catch (Exception ex){
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique se todos os campos foram preenchidos");
        }
    }
    
    private void limparCampos(){
        tfNome.setText("");
        tfIdade.setText("");
        tfDocumento.setText("");
        tfTipo.setText("");
        tfId.setText("");
        tfTelefone.setText("");
        tfEmail.setText("");
    }
    
    private boolean tipoDocumento(){
        int tipo;
        if(tfDocumento.getText().trim().length() == 11){
            tipo = 0;
            return true;
        } else if (tfDocumento.getText().trim().length() == 14){
            tipo = 1;
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Numero de digitos no campo 'Documento' não permitido");
        } 
        return false;
    }
    
    private void excluir(){
        if(tbConsultas.getSelectedRow() != -1){
            int ls = tbConsultas.convertRowIndexToModel(tbConsultas.getSelectedRow());
            pessoaControl.excluir(pessoas.get(ls).getId());
        }
        listar();
    }
    
    private void listar(){
        try{
            pessoas = pessoaControl.listarSQL("SELECT *\n FROM\n"
            + " public.tb_pessoas");
            mostrar(pessoas);
        } catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Pesquisa : " + ex.getLocalizedMessage());
        }
    }
    
    private void mostrar (List<PessoaBean> list){
        inicializando = true;
        while(tmConsulta.getRowCount() > 0){
            tmConsulta.removeRow(0);
        }
        inicializando = false;
        
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sem Registros");
        } else {
            String[] campos = new String[]{null, null, null, null}; 
            for(int i= 0; i < list.size(); i++){
                tmConsulta.addRow(campos);
                tmConsulta.setValueAt(list.get(i).getNome(), i, 0);
                tmConsulta.setValueAt(list.get(i).getIdade(), i, 1);
                tmConsulta.setValueAt(list.get(i).getDoc(), i, 2);
                tmConsulta.setValueAt(list.get(i).getTelefone(), i, 3);
                
            }
        }
    }
    
    protected void tbConsultaLinhaSelecionada(JTable tb){
        try {
            if(tb.getSelectedRow() != -1 && !inicializando){
                habilitarCampos();
                int ls = tbConsultas.convertRowIndexToModel(tb.getSelectedRow());
                tfNome.setText(pessoas.get(ls).getNome());
                tfIdade.setText(pessoas.get(ls).getIdade()+"");
                tfDocumento.setText(pessoas.get(ls).getDoc()+"");
                tfTipo.setText(pessoas.get(ls).getTipo()+"");
                tfId.setText(pessoas.get(ls).getId()+"");
                tfTelefone.setText(pessoas.get(ls).getTelefone()+"");
                tfEmail.setText(pessoas.get(ls).getEmail());
            } else {
                limparCampos();
            }
        } catch (Exception ex){
                ex.printStackTrace();;
        }
    }
    /*
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdc;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbConsultas;
    private javax.swing.JTextField tfDocumento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfTipo;
    // End of variables declaration//GEN-END:variables
}
