/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicioMeritoSwing;

import exercicioMeritoBeans.ProdutoBean;
import exercicioMeritoControls.ProdutoControl;
import exercicioMeritoTools.Tools;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingConstants;

/**
 *
 * @author Rafael
 */
public class CadProdutos extends javax.swing.JFrame {
    
    private final ProdutoControl produtoControl = new ProdutoControl();
    private DefaultTableModel tmConsulta = new DefaultTableModel(null, new String[]{"ID", "Nome", "Preço/L"});
    private ListSelectionModel lsConsulta;
    private List<ProdutoBean> produtos;
    private Boolean inicializando = true;
    

    /**
     * Creates new form CadProdutos
     */
    public CadProdutos() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("gas.png");
        this.setIconImage(img);
        desabilitarCampos();
        
        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centro = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centro.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);
        
        tbConsulta.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbConsulta.getColumnModel().getColumn(1).setPreferredWidth(30);
        tbConsulta.getColumnModel().getColumn(2).setPreferredWidth(20);
        
        tbConsulta.getColumnModel().getColumn(0).setCellRenderer(direita);
        tbConsulta.setAutoCreateRowSorter(true);
        tbConsulta.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                tbConsultaLinhaSelecionada(tbConsulta);
            }
        });
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        btAdc = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCombustivel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbConsulta.setModel(tmConsulta);
        jScrollPane1.setViewportView(tbConsulta);

        btAdc.setText("+");
        btAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdcActionPerformed(evt);
            }
        });

        btExcluir.setText("-");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        tfId.setEditable(false);
        tfId.setBorder(null);

        jLabel1.setText("ID:");

        jLabel2.setText("Combustível:");

        jLabel3.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(151, 151, 151)
                                        .addComponent(jLabel3)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSalvar)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdc)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdcActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_btAdcActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        salvar();
    }//GEN-LAST:event_btSalvarActionPerformed
    
    private void salvar(){
        if(tfCombustivel.getText().trim().isEmpty() || tfValor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Verifique se todos os campos foram preenchidos corretamente");
        } else {
            try {
                ProdutoBean bean = new ProdutoBean();
                
                bean.setNome(tfCombustivel.getText());
                bean.setValor(Double.parseDouble(tfValor.getText()));
                
                if(tfId.getText().trim().isEmpty()){
                    bean.setId(Tools.gerarId("com_id","tb_combustivel"));
                    produtoControl.cadastraProduto(bean);
                    limparCampos();
                } else {
                    bean.setId(Long.parseLong(tfId.getText()));
                    produtoControl.alteraProduto(bean);
                    limparCampos();
                }
                
                listar();
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar combustivel : "+ex);
            } 
        }       
    }
    
    private void excluir(){
        if(tbConsulta.getSelectedRow() != -1){
            int ls = tbConsulta.convertRowIndexToModel(tbConsulta.getSelectedRow());
            produtoControl.excluiProduto(produtos.get(ls).getId());
            listar();
        }
    }
    
    private void limparCampos(){
        tfId.setText("");
        tfCombustivel.setText("");
        tfValor.setText("");
    }
    
    private void habilitarCampos(){
        tfCombustivel.setEditable(true);
        tfValor.setEditable(true);
        btExcluir.setEnabled(true);
        btSalvar.setEnabled(true);
    }
    
    public void desabilitarCampos(){
        tfCombustivel.setEditable(false);
        tfValor.setEditable(false);
        btExcluir.setEnabled(false);
        btSalvar.setEnabled(false);
    }
    
    public void listar(){
        try {
            produtos = produtoControl.listarSQL("SELECT *\n"
                    + " FROM \n"
                    + " tb_combustivel");
            mostrar(produtos);
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void mostrar(List<ProdutoBean> lista){
        inicializando = true;
        while(tmConsulta.getRowCount()>0){
            tmConsulta.removeRow(0);
        }
        inicializando = false;
        
        if(lista.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum registro encontrado");
        } else {
            String[] campos = new String[]{null, null, null};
            for(int i = 0; i < lista.size(); i++){
                tmConsulta.addRow(campos);
                tmConsulta.setValueAt(lista.get(i).getId(), i, 0);
                tmConsulta.setValueAt(lista.get(i).getNome(), i, 1);
                tmConsulta.setValueAt(lista.get(i).getValor(), i, 2);
            }
        }
    }
    
    protected void tbConsultaLinhaSelecionada(JTable tb){
        try {
            if(tb.getSelectedRow() != -1 && !inicializando){
                habilitarCampos();
                int ls = tbConsulta.convertRowIndexToModel(tb.getSelectedRow());
                tfId.setText(produtos.get(ls).getId()+"");
                tfCombustivel.setText(produtos.get(ls).getNome());
                tfValor.setText(produtos.get(ls).getValor()+"");
            } else{
                limparCampos();
            }
        } catch (Exception ex){
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdc;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JTextField tfCombustivel;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
