/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicioMeritoSwing;

import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.WindowConstants;

/**
 *
 * @author Victória
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        menuInitAction();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadPessoa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmCadProdutos = new javax.swing.JMenuItem();
        jmPdv = new javax.swing.JMenu();
        jmPay = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        jmCadPessoa.setText("Cadastro de Pessoas");
        jmCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadPessoa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jmCadProdutos.setText("Cadastro de Produtos");
        jmCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jmCadProdutos);

        jMenuBar1.add(jMenu2);

        jmPdv.setText("jMenu1");

        jmPay.setText("PDV");
        jmPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPayActionPerformed(evt);
            }
        });
        jmPdv.add(jmPay);

        jMenuBar1.add(jmPdv);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadPessoaActionPerformed
        cadastrarPessoa();
    }//GEN-LAST:event_jmCadPessoaActionPerformed

    private void jmCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadProdutosActionPerformed
        //cadastrarProduto();       
    }//GEN-LAST:event_jmCadProdutosActionPerformed

    private void jmPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPayActionPerformed
        // abrirPDV();
    }//GEN-LAST:event_jmPayActionPerformed

    private void cadastrarPessoa(){
        CadPessoas pessoa = new CadPessoas();
        pessoa.pack();
        pessoa.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        pessoa.setLocationRelativeTo(null);
        pessoa.setVisible(true); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void menuInitAction(){
        jMenu1.setText("");
        jMenu2.setText("");
        jmPdv.setText("");
        ImageIcon icon = new ImageIcon("user.png");
        ImageIcon icon2 = new ImageIcon("gas.png");
        ImageIcon icon3 = new ImageIcon("pdv.png");
        Image image = icon.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        Image image2 = icon2.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        Image image3 = icon3.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        ImageIcon imagei = new ImageIcon(image);
        ImageIcon imagei2 = new ImageIcon(image2);
        ImageIcon imagei3 = new ImageIcon(image3);
        jMenu1.setIcon(imagei);
        jMenu2.setIcon(imagei2);
        jmPdv.setIcon(imagei3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmCadPessoa;
    private javax.swing.JMenuItem jmCadProdutos;
    private javax.swing.JMenuItem jmPay;
    private javax.swing.JMenu jmPdv;
    // End of variables declaration//GEN-END:variables
}
