/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicioMeritoSwing;

import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;

/**
 *
 * @author Rafael
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        menuInitAction();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.getImage("mercado.png");
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbBomba = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfQuantia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tfObs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfValorTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfCancela = new javax.swing.JButton();
        tfFinaliza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadPessoa = new javax.swing.JMenuItem();
        jmUsu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmCadProdutos = new javax.swing.JMenuItem();
        jmCadBombas = new javax.swing.JMenuItem();
        jmPdv = new javax.swing.JMenu();
        jmPay = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bomba:");

        cbBomba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Valor:");

        jLabel3.setText("R$:");

        jLabel4.setText("Quantidade:");

        tfQuantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQuantiaActionPerformed(evt);
            }
        });

        jLabel5.setText("L :");

        btCalcular.setText("Calcular");

        jLabel6.setText("Cliente:");

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Observações :");

        jLabel8.setText("Desconto :");

        jLabel9.setText("%");

        jLabel10.setText("Valor Total:");

        tfValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorTotalActionPerformed(evt);
            }
        });

        jLabel11.setText("R$:");

        tfCancela.setText("Cancelar");

        tfFinaliza.setText("Finalizar");

        jScrollPane1.setViewportView(tbConsulta);

        jMenu1.setText("File");

        jmCadPessoa.setText("Cadastro de Pessoas");
        jmCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadPessoa);

        jmUsu.setText("Cadastro de Usuário");
        jmUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuActionPerformed(evt);
            }
        });
        jMenu1.add(jmUsu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jmCadProdutos.setText("Cadastro de Produtos");
        jmCadProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadProdutosActionPerformed(evt);
            }
        });
        jMenu2.add(jmCadProdutos);

        jmCadBombas.setText("Cadastro de Bombas");
        jmCadBombas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadBombasActionPerformed(evt);
            }
        });
        jMenu2.add(jmCadBombas);

        jMenuBar1.add(jMenu2);

        jmPdv.setText("jMenu1");

        jmPay.setText("PDV");
        jmPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPayActionPerformed(evt);
            }
        });
        jmPdv.add(jmPay);

        jMenuBar1.add(jmPdv);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 172, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBomba, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(19, 19, 19)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(btCalcular))
                                        .addComponent(jLabel4)))
                                .addComponent(jLabel7)
                                .addComponent(tfObs)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfDes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(1, 1, 1)
                                    .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCancela)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfFinaliza))
                                .addComponent(jLabel10)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfQuantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tfCancela)
                    .addComponent(tfFinaliza))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadPessoaActionPerformed
        cadastrarPessoa();
    }//GEN-LAST:event_jmCadPessoaActionPerformed

    private void jmCadProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadProdutosActionPerformed
        cadastraProduto();       
    }//GEN-LAST:event_jmCadProdutosActionPerformed

    private void jmPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPayActionPerformed
        // abrirPDV();
    }//GEN-LAST:event_jmPayActionPerformed

    private void jmUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuActionPerformed
        cadastrarUsuario();
    }//GEN-LAST:event_jmUsuActionPerformed

    private void jmCadBombasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadBombasActionPerformed
        cadastrarBombas();
    }//GEN-LAST:event_jmCadBombasActionPerformed

    private void tfQuantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantiaActionPerformed

    private void tfValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorTotalActionPerformed

    private void cadastrarPessoa(){
        CadPessoas pessoa = new CadPessoas();
        pessoa.pack();
        pessoa.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        pessoa.setLocationRelativeTo(null);
        pessoa.setVisible(true); 
    }
    
    private void cadastrarUsuario(){
        CadUsu usu = new CadUsu();
        usu.pack();
        usu.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        usu.setLocationRelativeTo(null);
        usu.setVisible(true);
    }
    
    private void cadastraProduto(){
        CadProdutos prod = new CadProdutos();
        prod.pack();
        prod.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        prod.setLocationRelativeTo(null);
        prod.setVisible(true);
    }
    
    private void cadastrarBombas(){
        CadBomba b = new CadBomba();
        b.pack();
        b.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        b.setLocationRelativeTo(null);
        b.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void menuInitAction(){
        jMenu1.setText("");
        jMenu2.setText("");
        jmPdv.setText("");
        ImageIcon icon = new ImageIcon("user.png");
        ImageIcon icon2 = new ImageIcon("gas.png");
        ImageIcon icon3 = new ImageIcon("pdv.png");
        Image image = icon.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        Image image2 = icon2.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        Image image3 = icon3.getImage().getScaledInstance(22, 22,Image.SCALE_SMOOTH);
        ImageIcon imagei = new ImageIcon(image);
        ImageIcon imagei2 = new ImageIcon(image2);
        ImageIcon imagei3 = new ImageIcon(image3);
        jMenu1.setIcon(imagei);
        jMenu2.setIcon(imagei2);
        jmPdv.setIcon(imagei3);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JComboBox<String> cbBomba;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmCadBombas;
    private javax.swing.JMenuItem jmCadPessoa;
    private javax.swing.JMenuItem jmCadProdutos;
    private javax.swing.JMenuItem jmPay;
    private javax.swing.JMenu jmPdv;
    private javax.swing.JMenuItem jmUsu;
    private javax.swing.JTable tbConsulta;
    private javax.swing.JButton tfCancela;
    private javax.swing.JTextField tfDes;
    private javax.swing.JButton tfFinaliza;
    private javax.swing.JTextField tfObs;
    private javax.swing.JTextField tfQuantia;
    private javax.swing.JTextField tfValor;
    private javax.swing.JTextField tfValorTotal;
    // End of variables declaration//GEN-END:variables
}
